batch_size: 1
checkpoint: true
ckpt_freq: 100
data:
  data: ''
  eval_instruct_data: ''
  instruct:
    dynamic_chunk_fn_call: true
    shuffle: true
  instruct_data: /Users/luweiying/Documents/mistral-finetune/content/data/sampled_project_skill_question.jsonl
  shuffle: false
eval_freq: 100
log_freq: 1
lora:
  dropout: 0.0
  enable: true
  rank: 16
  scaling: 2.0
max_norm: 1.0
max_steps: 100
mlflow:
  experiment_name: null
  tracking_uri: null
model_id_or_path: /Users/luweiying/Documents/mistral-7B-v0.3
no_ckpt: false
no_eval: true
num_ckpt_keep: 3
num_microbatches: 1
optim:
  lr: 6.0e-05
  pct_start: 0.05
  weight_decay: 0.1
run_dir: ''
save_adapters: true
seed: 0
seq_len: 2048
wandb:
  key: None
  offline: false
  project: None
  run_name: None
world_size: 1
